### ISSUE TITLE
Promise.finally is undefined in iOS Safari less than 11.3

### ISSUE THREAD

**Issue by mark-slepkov** [lovasoa/whitebophir#100]
I have met this problem in iOS 10.3.3
This piece of code works incorrect because there is no `Promise.prototype.finally()` declared
```
this.socket.on("broadcast", function (msg) {
	handleMessage(msg).finally(function afterload() {
		var loadingEl = document.getElementById("loadingMessage");
		loadingEl.classList.add("hidden");
	});
});
```
And "Loading..." banner never hides

**Comment by mark-slepkov** [comment]
I temporarily solved this problem by adding Promise.finally polyfill. It would be great if you add similar polyfill in the project.

**Comment by lovasoa** [comment]
Thank you for reporting this
