### ISSUE TITLE
Translation instructions on README.md

### ISSUE THREAD

**Issue by ovari** [lovasoa/whitebophir#101]
1. Could you please advise how to translate this program?
2. Should the instructions also be shown in the [README.md](https://github.com/lovasoa/whitebophir/blob/master/README.md) file?

What do you think?

Thank you

**Comment by lovasoa** [comment]
Thanks for getting in touch !

I created a [detailed step-by-step translation guide](https://github.com/lovasoa/whitebophir/wiki/How-to-translate-WBO-into-your-own-language) to help users translate WBO, assuming no prior knowledge.

**Comment by ovari** [comment]
Should the instructions also ask that the translation be sorted alphabetically by locale? What do you think? Thank you

**Comment by lovasoa** [comment]
I actually like having english on the top, it makes it easier for new contributors. Is there a translation you can add ?

**Comment by ovari** [comment]
Yes, `hu` (Hungarian - magyar)
