### ISSUE TITLE
Unable to delete last character in text element

### ISSUE THREAD

**Issue by Sharath-GitBan** [lovasoa/whitebophir#107]
@lovasoa , I am not able to delete last character of the words written using Text tool.
Steps to reproduce
1)Write multiple texts at different places on a board
2)With text tool on, click on each word and delete all letters leaving the first letter of the word
3)Now with one letter left in all words, if we try to delete them now, letter gets deleted from input element but letter is still on the board, you can refer this board https://wbo.ophir.dev/boards/text

Thank you.

**Comment by lovasoa** [comment]
Thank you very much for reporting this bug, and thus making WBO better for everyone !
It's now fixed. You may have to hard-refresh (ctrl-shift-R) the page to purge your browser's cache and see the fix.
