### ISSUE TITLE
jitsi problem

### ISSUE THREAD

**Issue by alperbayata** [lovasoa/whitebophir#111]
I can't run wbo on jitsin domain address. I'm doing a reverse proxy not working

**Comment by lovasoa** [comment]
Hello and thank you for reaching out !
  Your issue needs more details to be actionable. Did you follow the instructions on our wiki about [how to setup WBO with jitsi](https://github.com/lovasoa/whitebophir/wiki/WBO-Jitsi-integration) ? What exact steps did you follow ? How and where did you install WBO ? What does not work ?
  If you give enough detailed information, then someone might be able to help you. You may also want to read and maybe comment on this thread about this topic: https://github.com/jitsi/jitsi-meet/issues/5295

**Comment by alperbayata** [comment]
yes i followed all the instructions.
my web service is nginx.

**Comment by alperbayata** [comment]
How can I make wbo always running on the server.

**Comment by alperbayata** [comment]
etherpad_base : 'https://wbo.ophir.dev/boards', 
It works when I do this address, but I want to run it on my server. :)

**Comment by lovasoa** [comment]
As I said, you need to provide much more details if you want this issue to be actionable.

> What exact steps did you follow ? How and where did you install WBO ? What does not work ?

You should provide a detailed list of everything you did, what you expected to happen, and what happened instead. One-line messages are not enough for anyone to be able to understand what's wrong.

**Comment by alperbayata** [comment]
I installed wbo as docker. I cannot integrate it into the video conference system.

**Comment by alperbayata** [comment]
How can I get ssl for wbo. What are the settings for nginx?

**Comment by lovasoa** [comment]
If you want to setup WBO behind a reverse proxy, see: https://github.com/lovasoa/whitebophir/wiki/Setup-behind-Reverse-Proxies

If you want to setup HTTPS on your website, once you have your reverse proxy, you can for instance use https://letsencrypt.org/

**Comment by alperbayata** [comment]
I need to configure the proxy settings for wbo in which file on the nginx server.
example: '/etc/nginx/sites-avaible/mydomain.com.conf' like this?

**Comment by lovasoa** [comment]
I encourage you to read the documentation on nginx to learn how to set it up. 
https://docs.nginx.com/nginx/admin-guide/basic-functionality/managing-configuration-files/

**Comment by alperbayata** [comment]
Thank you for your reply. mydomain.com:5001 When I click on the address, I get the error 'ERR_SSL_PROTOCOL_ERROR' My domain address has ssl.

**Comment by lovasoa** [comment]
This is not a problem with wbo but with your ssl configuration
