### ISSUE TITLE
How to enable wbo in jitsi? Participated in Wiki or failed

### ISSUE THREAD

**Issue by daxiondi** [lovasoa/whitebophir#117]
1. Etherpad has been installed and can be started successfully on jitsi

2. Add EP_ I don't know how to add etherpad to the plugin

`https://github.com/JohnMcLear/draw`

I think I have a problem here, but I don't know what to do

Three settings.json Add  end 

```
"ep_ draw":{

"host": "wbo_ host.tld " // http://localhost :5011
}
```
4. Use docker to start wbo.

5. Nginx configuration

```
location ^~ /etherpad/ {

proxy_ pass http://localhost :9001/;

proxy_ set_ header X-Forwarded-For $remote_ addr;

proxy_ buffering off;

proxy_ set_ header Host $host;

}



#whiteboard Drawing

location ^~ /draw/ {



rewrite /draw/d/(.*) /boards/$1 break;

proxy_ set_ header Upgrade $http_ upgrade;

proxy_ set_ header Connection "upgrade";

proxy_ pass http://localhost :8042/;

}

```

I want to see the following image, similar to
![image](https://user-images.githubusercontent.com/26639571/90624592-c5127580-e24a-11ea-954c-962d3856716f.png)
https://meet.ffmuc.net/www

But I can't find him. How can I open this button? I need help. I'm looking forward to your reply

**Comment by lovasoa** [comment]
Just tried  https://meet.ffmuc.net/www. It seems to be working correctly.

**Comment by daxiondi** [comment]
I have successfully integrated wbo into jitsi. Thank you for your reply. I hope wbo will be better and better

**Comment by lovasoa** [comment]
If you encountered issues that you resolved, them maybe you can update [our wiki page about the integration](https://github.com/lovasoa/whitebophir/wiki/WBO-Jitsi-integration) to make it clearer and easier to follow.
