### ISSUE TITLE
How to integrate this for docker-jitsi-meet ?

### ISSUE THREAD

**Issue by tusharsonawanes** [lovasoa/whitebophir#126]
How do I integrate this in the  docker-jitsi-meet instance where I have my etherpad already running ? Correct me if I am wrong, when I click the icon shown below in etherpad, my etherdraw should open.

![image](https://user-images.githubusercontent.com/12230324/91285896-62b9f780-e7ab-11ea-90d0-6a0da07da409.png)

**Comment by lovasoa** [comment]
The instructions for how to set  up WBO with jitsi are on our wiki : [*WBO-Jitsi integration*](https://github.com/lovasoa/whitebophir/wiki/WBO-Jitsi-integration). Feel free to open an issue here if something doesn't work.
