### ISSUE TITLE
Integration with jitsi / docker-jitsi-meet

### ISSUE THREAD

**Issue by tusharsonawanes** [lovasoa/whitebophir#128]
Hello, I am running docker-jitsi-meet instance and I have configured etherpad, which is running **successfully** as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/12230324/91531403-60ca7280-e92a-11ea-9b7b-a153faf5f757.png)

1. Taking a shell of the etherpad container, I installed the plugin `ep_draw` by firing `npm i ep_draw` and when I click Open shared document, I see that the drawing tool symbol is added there as seen below

![image](https://user-images.githubusercontent.com/12230324/91532344-d08d2d00-e92b-11ea-95cd-ac650f42ab98.png)

2. I am also running a separate wbo container using this command - `docker run -it --publish 5001:80 --volume $(pwd)/wbo-boards:/opt/app/server-data lovasoa/wbo:latest ` as mentioned in the official repo and I can successfully access it on port 5001

![image](https://user-images.githubusercontent.com/12230324/91532843-88223f00-e92c-11ea-92d9-66583f772bf9.png)

What I want is, 

a. When I click the drawing tool symbol, as mentioned in point no. 1 above, the wbo-board should open. So I will have Etherpad working with WBO-whiteboard. I went through the [documentation](https://github.com/lovasoa/whitebophir/wiki/WBO-Jitsi-integration), but when I add 

```
"ep_draw":{
        "host": "wbo_host.tld"
    }
```

to settings.json, my container crashes

b. And where do I add the nginx configurations ? I couldn't understand where to put the nginx configurations. 

Any help on this ?

**Comment by lovasoa** [comment]
what does your settings.json look like ? What is the error message when it crashes ?

**Comment by lovasoa** [comment]
You should replace `wbo_host.tld` with the domain name of the host where you installed wbo.

**Comment by tusharsonawanes** [comment]
> 
> 
> You should replace `wbo_host.tld` with the domain name of the host where you installed wbo.

@lovasoa  thank you for the quick response. 
Wbo is installed as a docker container on the same machine and is running on port 5001. I added these lines in `settings.json`

```

"ep_draw":{
        "host": "http://<machineip>:5001"
    },

```
I forgot to add a comma in the end because of which the container was crashing. Now what is happening is, as soon as I restart the container after adding the above code, **the `ep_draw` icon disappears** from the etherpad instance.

I also see two files, `settings.json` and `settings.json.docker`. I am adding the above in settings.json

Just to let you know, I am running the container with this command  `docker exec -it --user="root" 51eab32bce57 bash`

Not running with root doesnt let me update and install vim, which is used to make changes in the settings.json file.

**Comment by tusharsonawanes** [comment]
@lovasoa any help with this ?

**Comment by tusharsonawanes** [comment]
From the logs, it is seen that the browser is sending an `https://` request to the ep_draw instance. It I removed the `http://` in front of the machine ip, because it showed something like `https://http://machineip:5001/boards/anonymous/`,  but stilll it is sending `https://` request to the ep_draw instance.

**Comment by JIBSIL** [comment]
I recently published a modified version of ep draw designed to use WBO.
https://www.npmjs.com/package/ep_whiteboard
If you do this, you do not need to use a reverse proxy.

**Comment by tusharsonawanes** [comment]
@JIBSIL let me try it

**Comment by tusharsonawanes** [comment]
Thanks, since it's a part of jitsi now, closing this.
