### ISSUE TITLE
Sub folder to store board json files

### ISSUE THREAD

**Issue by Sharath-GitBan** [lovasoa/whitebophir#129]
Hi, 

 I would like to create sub folders under ./wbo/server-data/ based on type of board to store board json files. How can I implement this, and also how to render the boards from a particular subfolder.

**Comment by lovasoa** [comment]
Hi,
  I'm closing this since it is not an issue, but we can continue the discussion below.

**Comment by lovasoa** [comment]
Here is the place in the code where the location of the board file is determined: 
https://github.com/lovasoa/whitebophir/blob/master/server/boardData.js#L40

However, I'm not sure I understand what you mean by *type of board*. There is currently no such concept in wbo.

**Comment by lovasoa** [comment]
To render a board, you can access `/preview/<board name>` on a running server. For instance: https://wbo.ophir.dev/preview/anonymous

Locally, you can also use the create svg script like so: `node server/createSVG.js /path/to/board-name.json`

If you want to render all the boards in a particular folder, you can iterate over all the name of the boards in this folder 👍 

```bash
for file in server-data/
do
    node server/createSVG.js "$file" > "$file.rendered.svg"
done
```

**Comment by Sharath-GitBan** [comment]
Hey,what I meant actually is can we dynamically create sub folders under server-data to store board files instead of storing them at one place by default. For eg, consider when users create boards, I want store some board files under /server-data/sub-folder1 and some under /server-data/sub-folder2.

**Comment by lovasoa** [comment]
Yes, I got that. What I don't get is what you mean by *type of board*. How will you decide which board goes to which folder ?

**Comment by lovasoa** [comment]
Also, friendly reminder: if you make your own version of wbo which includes changes, you have to make them public, according the projects license.

Where is your source code located ?
