### ISSUE TITLE
how do i start whitebophir as a service in linux

### ISSUE THREAD

**Issue by alperbayata** [lovasoa/whitebophir#138]
how do i start whitebophir as a service in linux

**Comment by lovasoa** [comment]
The easiest and safest is probably to use the wbo docker image and launch it with --restart

**Comment by alperbayata** [comment]
The docker exec -it <container-name> bash command does not work so I can edit the files by myself. How can I edit files in docker?

**Comment by lovasoa** [comment]
What do you mean by "edit the files" ? Edit the board Json files, or the code? 

If you want to access the boards, just mount the server-data folder as instructed in the readme. 

If you want to edit the code, the best is to fork this repo and build your own container with docker build. Also, a friendly reminder: if you make any modification to the code, however small it is, you have to publish and distribute your version under the same open source license as wbo itself.

**Comment by alperbayata** [comment]
thank you :)
