### ISSUE TITLE
[Request] Add arm64 and armhf support to docker image

### ISSUE THREAD

**Issue by netthier** [lovasoa/whitebophir#142]
I'd like to host my own instance of this on my arm64 SBC, and since node.js is pretty much cross-platform, creating additional docker images for both arm64 and armhf shouldn't be too complicated.
Most Linuxserver.io docker images implement multi-arch support, so their repositories could serve as a source of inspiration.

**Comment by lovasoa** [comment]
You should already be able to build the image for arm from the dockerfile in this repository. For the version hosted on docker hub, it's built by docker hub itself. Do they offer arm builds?

**Comment by netthier** [comment]
Yes, dockerhub allows for multi-arch builds, here's an example by linuxserver.io: https://hub.docker.com/r/linuxserver/wireguard/tags
I think here's a "tutorial", for how it's done, although I don't think qemu would be required in this case: https://hub.docker.com/r/ckulka/multi-arch-example

**Comment by lovasoa** [comment]
ok. Pull requests welcome!

**Comment by lovasoa** [comment]
Starting with lovasoa/wbo:v1.14.0 we have builds for amd, arm64 and armv7.
