### ISSUE TITLE
How long do whiteboards exist?

### ISSUE THREAD

**Issue by 54sledgehammer45** [lovasoa/whitebophir#143]
One can create whiteboards, but how long do they stay on the server (if that's how they're stored)? Especially private ones: are they deleted when everybody leaves the room? Is there a time limit?

I think if there's no limit, one should exist (at least for private ones). And it should be specified in the README or on the frontpage (maybe even on the whiteboard)

**Comment by lovasoa** [comment]
No, whiteboards are never deleted by wbo itself. 

On wbo.ophir.dev, there is an external script that deletes unused whiteboards after 90 days of inactivity. 

Would you be interested in implementing such a feature in WBO ?
