### ISSUE TITLE
Multiple Whiteboard Pages/Tabs

### ISSUE THREAD

**Issue by fabiorosito** [lovasoa/whitebophir#144]
It would be interesting and useful to implement a feature that allows a user to open new canvas "pages" within the same session. Would this be feasible to implement? I'm not sure if a similar issue/feature has been noted already, but please redirect me if it has!

**Comment by lovasoa** [comment]
There is no notion of *pages* in WBO, that's the point of creating an infinite whiteboard. Drawings are not limited to a set area. If you want to split your board into multiple parts, you can simply draw multiple rectangles and use them as "pages".

**Comment by marekyggdrasil** [comment]
@lovasoa I think this is good to stick with projects philosophy and I respect that. I think such behaviour could be simulated without violating those principles. We could use menu buttons such as "previous page" an "next page" that would move the view by size of single screen. Do you think such feature proposal would be reasonable?
