### ISSUE TITLE
Docker Pull failed on Window Powershell

### ISSUE THREAD

**Issue by wandesky** [lovasoa/whitebophir#146]
When pulling the image from Docker hub, the error shown in the image below is thrown
docker: “invalid reference format”

![DockerErrorWhitebophir](https://user-images.githubusercontent.com/19204205/99192915-6e71e600-272a-11eb-9e28-ba85369f7dbc.PNG)

**Comment by wandesky** [comment]
Docker is seeing something unexpected before the image name, making it think something in the command other than the `lovasoa/wbo:latest` is the image name.

Running `docker run -it --publish 5001:80 --volume "$(pwd)/wbo-boards:/opt/app/server-data" lovasoa/wbo:latest` should fix the issue

Merging [Pull Request 147](https://github.com/lovasoa/whitebophir/pull/147) will probably prevent this error from ever showing again, at least for Windows Powershell users.

**Comment by lovasoa** [comment]
I updated the readme to make it explicit that the command in the  README was for [bash](https://www.gnu.org/software/bash/). The `$(...)` syntax does not exist in powershell. 

You can either use [WSL](https://docs.microsoft.com/en-us/windows/wsl/) to use normal linux commands on windows, or adapt the line to powershell. You can remove `--volume $(pwd)/wbo-boards:/opt/app/server-data` from the command altogether, if you don't need to persist your whiteboards, or create your persistence folder manually and use `--volume path\to\your\wbo-boards\folder:/opt/app/server-data`

**Comment by wandesky** [comment]
Adding the double quotes worked and I was able to pull and deploy on my PC.
If adding the double quotes does not affect bash users, then adding them will surely help out others who wish to pull the image from a Windows environment.
