### ISSUE TITLE
Option to export to pdf/jpg/...

### ISSUE THREAD

**Issue by tobiasBora** [lovasoa/whitebophir#15]
First thanks for this really nice tool (the only open source one I can find on the whole internet so far...). But it still lacks a feature I'd really love to have: the ability to export the drawing into another format (png for example). It would be great to be able to save a document.

Thanks!

**Comment by gerhardbeck** [comment]
Yeah, that would be really great

**Comment by lovasoa** [comment]
Yes, that would be nice ! Would one of you want to try making a pull request ? I could provide technical assistance.

**Comment by gerhardbeck** [comment]
Good offer, but Sorry, I can't. I'm just too busy these days and don't want to promise anything I know I won't be able to keep

**Comment by bcag2** [comment]
SVG (vector) and PNG formats are for me the best for this drawing sort

**Comment by ramsonline** [comment]
I would like to see this Issue reopened since PNG, PDF or JPG are way more convenient in most offices than the SVG Format.
Currently only SVG seems to be implemented.

**Comment by bcag2** [comment]
@eckad158 could you be more precise about "most offices" ?  
Perhaps you should ask to your offices software dev to support this web de facto standard ?  
Libre Office 6.0… supports SVG as well as any popular web navigator
