### ISSUE TITLE
permission denied 

### ISSUE THREAD

**Issue by MR-UNKNOWN2000** [lovasoa/whitebophir#156]
it doesnt let me download it

**Comment by lovasoa** [comment]
Hello!
  We need more information to look into your problem. What are the precise steps you are taking, what is happening, and what did you expect to happen instead?

**Comment by MR-UNKNOWN2000** [comment]
i was following the "without container" guide and  this happened 
![image](https://user-images.githubusercontent.com/59323333/101351902-3d985300-3889-11eb-948e-72601c0f8902.png)

**Comment by MR-UNKNOWN2000** [comment]
and I have tried docker 
![image](https://user-images.githubusercontent.com/59323333/101352399-ff4f6380-3889-11eb-8a30-f1884dd7cd53.png)

**Comment by lovasoa** [comment]
> and I have tried docker
> ![image](https://user-images.githubusercontent.com/59323333/101352399-ff4f6380-3889-11eb-8a30-f1884dd7cd53.png)

See https://docs.docker.com/engine/install/linux-postinstall/

**Comment by lovasoa** [comment]
I updated the README to clone the repo through HTTPS to allow cloning anonymously.

```bash
git clone https://github.com/lovasoa/whitebophir.git
```
