### ISSUE TITLE
Icons can be hidden on depending on the screen size

### ISSUE THREAD

**Issue by piiskop** [lovasoa/whitebophir#163]
![Screenshot from 2021-01-19 14-53-19](https://user-images.githubusercontent.com/14224528/105037244-5db15980-5a66-11eb-89a5-4d40198e66f3.png)
Please see from the screenshot that the icon for opacity is hidden. These buttons should appear independent of the screen size.

**Comment by lovasoa** [comment]
The toolbar is scrollable, so you can still access icons at the botton anyway. But I do agree that the user experience is not great. Pull request welcome !

**Comment by piiskop** [comment]
What do you mean by telling that the toolbar is scrollable? Is there a hidden scrollbar somewhere? It doesn't scroll with the board and the board is scrollable. Even on my screenshot, you don't see a scrollbar for the menu. So what do you mean it's scrollable?

I usually avoid intervening in developments of third-party software. I do my own software and report issues on other software. This is because styles and principles are different.

**Comment by lovasoa** [comment]
> So what do you mean it's scrollable?

You can place your mouse on an icon and use your mousewheel to scroll.

> I usually avoid intervening in developments of third-party software. I do my own software and report issues on other software. This is because styles and principles are different.

Of course you are free to contribute or not. I was just highlighting that if you want this feature to be implemented quickly (or at all), the best way is to make a pull request yourself.

**Comment by piiskop** [comment]
I just did as you instructed: placed my mouse cursor on an icon and used the mousewheel to scroll. The only thing scrolled was the board while the buttons remained at their initial fixed place without scrolling anywhere.

You can't assume that a user has a mouse neither. I prefer using an electronic pen for graphical processes. The pen has no scrolling options.

**Comment by lovasoa** [comment]
I do agree that the user experience is not great, I'm leaving this open. PR welcome !

**Comment by sents** [comment]
The scrolling works for me on Firefox but not with Chromium. I've tried to find the issue but I had no luck yet.

**Comment by sents** [comment]
I've found that scrolling the menu bar works on Chromium if `Threaded scrolling` is disabled in `chrome://flags`.

**Comment by sents** [comment]
As a workaround for Chrome users with enabled `Threaded scrolling` one could set `tabindex="0"` for the menu element. That way users can tab into the menu bar and scroll it using the arrow keys. That doesn't solve the issue for tablets though.

**Comment by piiskop** [comment]
Exactly: this is no solution. Users should be able to use any web apps without tweaking their browsers. It's not about just me. It's about my pupils and other people who use the same whiteboards  as I do.
