### ISSUE TITLE
Problem in installation 

### ISSUE THREAD

**Issue by mohammadwakeel** [lovasoa/whitebophir#17]
I'm using first time Whiteboard. i'm facing a problem in installing whitebophir. please can you guide me.

**Comment by lovasoa** [comment]
Hello!
  You should give more information if you want your bug report to be actionable. 

   What are you doing exactly? What commands are you entering ? What behavior did you expect? What did you see instead?

Please be as specific as you can.

**Comment by lovasoa** [comment]
I am closing this since there was no answer. You can still comment.
