### ISSUE TITLE
How to run this via PM2?

### ISSUE THREAD

**Issue by Patrick-Vogt** [lovasoa/whitebophir#175]
Hello, 
first of all - thank you for this great plugin - it works like a charm! 

I usually have all my node / npm things running via PM2.
But using commands like:

PORT=5001 pm2 start npm --name "whiteboard"
pm2 start ./server/server.js (After setting the port manually in the configuration)

doesn't seem to work - Nginx returns "502 Bad Gateway".

Is there any other way to solve this, without using "npm start PORT=5001 " ?

Thank you!

**Comment by Patrick-Vogt** [comment]
Sorry, it was late and I solved it with "sudo pm2 server.js" :D

**Comment by lovasoa** [comment]
As a note to future users: it is probably not a great idea security-wise to run pm2 as root.
