### ISSUE TITLE
Ability to export/import board using local files

### ISSUE THREAD

**Issue by PierceBeckett** [lovasoa/whitebophir#177]
It would be super useful to have the ability to export the current board as a file to my local machine, where i can then later use that file to create a new board on a different wbo server

**Comment by lovasoa** [comment]
Hello,
  This is already possible, but the feature is not documented.
  You can access https://wbo.ophir.dev/download/my_board_name (where my_board_name) is the name of your board to download wbo file.
   Then you can place this file in `server_data/board-my_board_name.json` on your other server, and voilà, your board is migrated.
  
  This is a hidden feature oriented towards board administrators. I wouldn't like users to be able to fully erase a board by uploading another one in its place.

**Comment by PierceBeckett** [comment]
super! just what i needed thanks

**Comment by piiskop** [comment]
The problem with the download is that it fills the objects with black color and texts aren't visible after removing the filling manually. Using the preview functionality, that anomaly doesn't happen.
