### ISSUE TITLE
starting server times out

### ISSUE THREAD

**Issue by gsutay** [lovasoa/whitebophir#18]
Hi, very nice tool!  I like the demo and I am trying to run it local now.

I have:
0. -bash-4.2# cat /etc/redhat-release
   Red Hat Enterprise Linux Server release 7.6 (Maipo)
1. downloaded repos zip
2. unzip in /whitebophir
3. cd /whitebophir/whitebophir-master
4. npm install -d
  (installed clean, no errors)
5. vim ./server/server.js
  (changed port 8080 to 8000)
5. npm run start
  -bash-4.2# npm run start

> whitebophir@1.0.24 start /whitebophir/whitebophir-master
> node ./server/server.js

2020-02-29T08:55:15.975Z        server started  {"port":8000}

Opening my localhost:8000 in browser shows empty page and times out.

Did I miss something?  Any ideas?

**Comment by lovasoa** [comment]
Hello, 
  Thank you for reporting this. However, I cannot reproduce the error.
   Also: if you want to start the server on a different port **you should not change the source code** ! Just set the `PORT` environment variable like so : 

```
PORT=9595 npm run start
```

Your issue really does not seem to be tied to whitebophir. Can you try to paste the following in a file named `test.js`: 

```js
require('http').createServer((req, res) => {
  res.end('Hello World');
}).listen(8000);
```

and then run `node test.js`, open `localhost:8000` in your browser, and report whether you see `Hello World` ?

**Comment by gsutay** [comment]
Hi,

Thank you!  Your test worked on port 80 but not 8000 or 9595 which proved it was a port blocking issue on my network config side.

Works AWESOME now!!! :D 

What do you think of this idea?  Wrap it with a UI that has pre-defined boards and extended features like screen capture, save/load?

Cheers,
Gene

**Comment by lovasoa** [comment]
I'm not sure I understand you proposal. Can you elaborate ?
Being able to export the board is already a pending feature request, see: https://github.com/lovasoa/whitebophir/issues/15

If you want to implement it, a pull request would be welcome !
