### ISSUE TITLE
To enable WBO by default in etherpad.

### ISSUE THREAD

**Issue by researchbrain** [lovasoa/whitebophir#185]
Hello, I am running docker-jitsi-meet instance and I have configured etherpad, which is running successfully.
I went through the  [documentation](https://github.com/lovasoa/whitebophir/wiki/WBO-Jitsi-integration).
Taking a shell of the etherpad container, I installed the plugin ep_whiteboard by firing npm i ep_whiteboard, and done some addition in settings.json.
```javascript

"ep_draw": {
        "host": "IPAdress:5001",
         "onByDefault": true,
         "position": "right"
   },
```
On browser, When I click the drawing tool symbol, the wbo-board gets open. Therefore, I  have Etherpad working with WBO-whiteboard.

![image](https://user-images.githubusercontent.com/83460263/116863781-6f3cfc80-ac24-11eb-9ce6-9b60b88f503a.png)

What I want is,
Even after adding "onByDefault": true in settings.json, I still need to click on drawing tool symbol to bring the scribble pad up, it should be there by default.
Any help on this ?

**Comment by lovasoa** [comment]
This seems to be an issue for ep_whiteboard, not WBO.
