### ISSUE TITLE
Adding ep_draw to settings.json

### ISSUE THREAD

**Issue by timowevel03** [lovasoa/whitebophir#191]
Hello,

I installed ep_whiteboard. As soon as I add  "ep_draw":{
        "host": "wbo_host.tld"
    }
to the settings.json (with my WBO server) it won't boot anymore. Where exactly do I have to add it?

Thanks.

**Comment by lovasoa** [comment]
I think this is a problem with your ep_whiteboard, not a bug in WBO.

**Comment by timowevel03** [comment]
Indeed, I had to add a "," after the "}".
