### ISSUE TITLE
Config Flag to make board view-only by default  using hideMenu

### ISSUE THREAD

**Issue by SushantGautam** [lovasoa/whitebophir#210]
For private instances, where the boards are embedded in like IFRAMEs,  it would be great to make boards read-only by defaults with Some Config Flag.
This will be a kind of weak security for use cases **when we want boards to be read-only** most of the time. 
And, it can be made editable with ?hideMenu=false or something like that.
Also, even if the URL is exposed, it won't be easy to guess or find a way to edit it.

Relates to
#84 #116 #150

**Comment by lovasoa** [comment]
This would be a dangerous approach. hideMenu just hides the menu, it doesn't make the board read only.

**Comment by SushantGautam** [comment]
If the need is to make **boards be read-only most of the time**, I think **without any authentication** system, this can be a cheap idea. 
It's true that **hideMenu** is insecure, we also make some way to **disable message being sent in the socket-** only receive.
There is something like that implemented at **https://quicknote.io/ without authentication.**
Most notes are read-only and the edit link is saved in the browser.

This is not a security feature but a UI need for various use cases. 

We can add a similar way, for eg: **including some params in the browser to make it editable.**
Of course, the default behavior for the public board doesn't sound great with this idea. But for self-hosted cases, this can be great for integration in multiple ways. Such behavior can be made to be enabled with some flags in the config.

**Comment by lovasoa** [comment]
You already have `hideMenu` when all you want is to not show the menu. I think with `hideMenu=true` in the URL, it's quite clear what is going on. Without it, it would give the user the impression that the board is read-only whereas it can in fact be edited.
