### ISSUE TITLE
how to configure ssl on self hosted wbo

### ISSUE THREAD

**Issue by Interspace7** [lovasoa/whitebophir#215]
how to enable ssl on self hosted wbo,  for me http working fine on self hosted server, then tried to modify http to https by changing server/server.js like as follows

```
var express = require('express');
var https = require('https');
var fs = require('fs');
var options = {
  key: fs.readFileSync('..............),
  cert: fs.readFileSync('................')
};
var app =https.createServer(options, express());
```

it enable ssl url and server started , but browser shows 

`Cannot GET /boards/<board_id>`

**Comment by lovasoa** [comment]
you can use the instructions on the wiki to configure a reverse proxy such as nginx. It will handle ssl, but also caching and many other things

**Comment by elearningdienst** [comment]
The nginx proxy works great and with a good performance. I would recommend that as well.
