### ISSUE TITLE
Unable to run this project on "Node JS - AWS Lightsail instance"

### ISSUE THREAD

**Issue by rohitcoder** [lovasoa/whitebophir#22]
Hi @lovasoa ,

Thanks for creating this awesome project and making it public!
Can you please help me with installation on a remote server?

I installed this on my localhost and everything seems working. I used

``` 
Git clone https://github.com/lovasoa/whitebophir/
npm install
npm start
```

But, when I do this same on my AWS instance. its just listing all files and directories "index of/"

I also got this kind of response on my CLI 
```json
server started	{"port":8080}
```
Can you please help me fixing it ASAP?

Thanks,
Rohit Kumar

**Comment by lovasoa** [comment]
It looks like the server started successfully on your remote instance, on port 8080, but you are trying to access the server on port 80, where something else (probably a default apache or nginx installation) is running.

**Comment by lovasoa** [comment]
You can start WBO on a custom port by setting the `PORT` environment variable

**Comment by lovasoa** [comment]
@rohitcoder Did this solve your issue ?

**Comment by rohitcoder** [comment]
Hi @lovasoa ,

I was busy with something else. I'm checking it right now, and I'll let you know the status in comments :)

**Comment by rohitcoder** [comment]
Hi @lovasoa ,

I am not getting any output its just keep loading http://15.206.150.130:9090/

this command i used
```
export PORT=9090
cd whitebophir
npm install
npm start
```
Response:
```
server started{"port":9090}
```
Any suggestions?

**Comment by lovasoa** [comment]
Is port 9090 accessible from the outside on your server?

**Comment by lovasoa** [comment]
anyway, the issue doesn't seem to be related to wbo.

**Comment by rohitcoder** [comment]
Hi @lovasoa ,

Problem solved! We can close this report. After setting PORT i configured my firewall to allow PORT 9090 and it fixed this issue.

Again many many thanks for this project. Keep rocking bro! :)
And be safe from Corona Virus :)

We can close this report now.

Thanks,
Rohit

**Comment by lovasoa** [comment]
You're welcome! Have fun with wbo :)
