### ISSUE TITLE
Such a beautiful, simple, shared concept

### ISSUE THREAD

**Issue by NortySpock** [lovasoa/whitebophir#221]
Thanks for writing this, I loved playing around with it on two screens, with it hosted in a docker container on my Raspberry Pi I use as a home server. (built it for armhf using the Dockerfile, then spun it up with docker-compose)  I'm hoping this nestles into my collection of containers alongside a few others and becomes a happy, welcomed member of the family. 

Such a simple, elegant presentation. Everything you wanted in tool selection, nothing you didn't. _(I'm sure you'll find reason to add a few more paint tools, I totally understand.)_ 

I just wanted to say, @lovasoa , thank you for writing this collaborative whiteboard and sharing it with the world.

**Comment by lovasoa** [comment]
Thank you very much for your kind words!
