### ISSUE TITLE
facing issue to delete point or thin line

### ISSUE THREAD

**Issue by ravi2004** [lovasoa/whitebophir#226]
This is very tuff if user want to erase a dot or thin line 

need to some selection like tool for delete or erase the graphic item .
Could you please check if this is possible. as some where user can take benefit for this,

**Comment by lovasoa** [comment]
There is already a selection tool, which is the secondary tool in the "hand" button

![image](https://user-images.githubusercontent.com/552629/148101172-3f07fe33-e5eb-4742-9b98-18d27e2f8e41.png)
