### ISSUE TITLE
vulnerable packages

### ISSUE THREAD

**Issue by drgray20** [lovasoa/whitebophir#229]
Hi during continuous monitoring of our whitebophir image, our scanners picked up the following vulnerable packages, 
engine.io-5.2.0 patched in versions 4.1.2, 5.2.1, 6.1.1.
uglify-js-3.14.2 patched in => uglify-js-3.14.4
request-2.88.2, request project has been abandoned, recommend switching to a different http request client. 
Please when will these high vulnerabilities be patched?
Please let me know

**Comment by lovasoa** [comment]
Hello, does any of the mentioned vulnerabilities actually impact wbo, or is this just an automated report that you haven't tested?
