### ISSUE TITLE
zoom button cannot dezoom

### ISSUE THREAD

**Issue by S-poony** [lovasoa/whitebophir#23]
the "zoom button" doesn't allow you to dezoom (I know you can do it with mouse but still)

**Comment by lovasoa** [comment]
Hello my little spoony :) As documented in the tooltip that appears when you hover over the board with the zoom tool selected, you can dezoom by keeping shift pressed when clicking.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/552629/78118952-feffee00-7407-11ea-8cc5-394cbfdd7e5f.png">

**Comment by topninja** [comment]
how to make zoom out button on buttons list?

**Comment by lovasoa** [comment]
@topninja The zoom tool is used for both zooming in and out.

**Comment by topninja** [comment]
hi @lovasoa   thnaks for your reply
I know aobut that. 
if shift+click then can use zoom out feature.
but I want to make zoom out button as more on list.

**Comment by lovasoa** [comment]
You can open a pull request with a proposition and we'll discuss it.
