### ISSUE TITLE
Service restart fails with "MODULE_NOT_FOUND" after upgrading the source code

### ISSUE THREAD

**Issue by piiskop** [lovasoa/whitebophir#246]
i had _whitebophir_'s files lately from February 6, 2021. Now, i pulled an upgrade and can't run the system service anymore:

kalmer@test:/projektid/whitebophir$ `sudo systemctl status whitebophir.service` 

> ● whitebophir.service - whiteboard application
>      Loaded: loaded (/etc/systemd/system/whitebophir.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Sat 2022-05-28 17:44:41 EEST; 5s ago
>     Process: 650734 ExecStart=/usr/local/bin/node /projektid/whitebophir/server/server.js > /projektid/whitebophir/output.log 2> /projektid/whitebophir/error.log (code=exited, status=1/FAILURE)
>    Main PID: 650734 (code=exited, status=1/FAILURE)
> 
> mai   28 17:44:41 test.tennis24.ee node[650734]:     at Module.require (node:internal/modules/cjs/loader:1005:19) {
> mai   28 17:44:41 test.tennis24.ee node[650734]:   code: 'MODULE_NOT_FOUND',
> mai   28 17:44:41 test.tennis24.ee node[650734]:   requireStack: [
> mai   28 17:44:41 test.tennis24.ee node[650734]:     '/projektid/whitebophir/server/log.js',
> mai   28 17:44:41 test.tennis24.ee node[650734]:     '/projektid/whitebophir/server/sockets.js',
> mai   28 17:44:41 test.tennis24.ee node[650734]:     '/projektid/whitebophir/server/server.js'
> mai   28 17:44:41 test.tennis24.ee node[650734]:   ]
> mai   28 17:44:41 test.tennis24.ee node[650734]: }
> mai   28 17:44:41 test.tennis24.ee systemd[1]: whitebophir.service: Main process exited, code=exited, status=1/FAILURE
> mai   28 17:44:41 test.tennis24.ee systemd[1]: whitebophir.service: Failed with result 'exit-code'.
> 

The content of the service file:

> [Unit]
> Description=whiteboard application
> 
> [Service]
> User=www-data
> WorkingDirectory=/projektid/whitebophir
> ExecStart=/usr/local/bin/node /projektid/whitebophir/server/server.js > /projektid/whitebophir/output.log 2> /projektid/whitebophir/error.log
> Environment=PORT=1024
> [Install]
> WantedBy=multi-user.target
>

**Comment by lovasoa** [comment]
You can't just git pull the code to update !

If you don't want to handle the manual update, then you should use docker, where you can just pull the latest version and everything just works.

**Comment by piiskop** [comment]
What do you mean by manual update?

**Comment by lovasoa** [comment]
What you did: just copying the new code

**Comment by piiskop** [comment]
What else should i do?

**Comment by lovasoa** [comment]
use docker
