### ISSUE TITLE
How to hide controls based on configuration ?

### ISSUE THREAD

**Issue by AjayShivanagol** [lovasoa/whitebophir#252]
I have integrated whitebophir in my project.

I have this scenario.
Moderators initiate the whiteboard but non-moderator should not have the access to controls.
like he should not modify the whiteboard is there a way to control it via Configuration ?

**Comment by lovasoa** [comment]
Hello and thank you for using WBO !
You can hide the menu by adding `?hideMenu=true` at the end of the URL of a board.

For instance: https://wbo.ophir.dev/boards/test?hideMenu=true

**Comment by lovasoa** [comment]
For more information, see https://github.com/lovasoa/whitebophir/issues/150
