### ISSUE TITLE
Board name in JWT

### ISSUE THREAD

**Issue by holema** [lovasoa/whitebophir#253]
Hello,
thanks for the great tool. I realy love what you have build here.

I have a question concerning the JWT, is it possible to add the board name in the jwt. Because up to now, if I know the board name, I can enter the board with any valid key. 
I think it would be very helpfull, if the board name is also in the jwt and is protected like the role. So you have to get the correct JWT for this specific room.

Best regards

**Comment by lovasoa** [comment]
That would be a great feature ! PR welcome ! But we need to take care of staying backwards-compatible.

**Comment by holema** [comment]
Hello I added a PR to this feature.

**Comment by holema** [comment]
#254 closes this issue
