### ISSUE TITLE
How to delete user from specific connected board by socket.id or any other method.

### ISSUE THREAD

**Issue by rohitcoder** [lovasoa/whitebophir#27]
Hi @lovasoa 

I am trying to modify some parts of code, and I am working on introducing new features for this tool. I am stuck on a part where i want to delete a connected user from a specific board. Can you please suggest me or guide me how to achieve that?

I tried doing it with this, but i wasn't able to do it. 
```javascript
board.users.delete(socket.id);
```
I picked this above code snippet from server/socket.js
```javascript
socket.on('disconnecting', function onDisconnecting(reason) {
		Object.keys(socket.rooms).forEach(function disconnectFrom(room) {
			if (boards.hasOwnProperty(room)) {
				boards[room].then(board => {
					board.users.delete(socket.id);
					var userCount = board.users.size;
					log('disconnection', { 'board': board.name, 'users': board.users.size });
					if (userCount === 0) {
						board.save();
						delete boards[room];
					}
				});
			}
		});
	});
}
```

### Summary:
I just want to remove a connected user from a specific board.

Thanks,
Rohit

**Comment by lovasoa** [comment]
Hello! Can you share your work on wbo ? Can you make your version public on GitHub?

**Comment by rohitcoder** [comment]
Hi @lovasoa 

I'll surely make my version public within few weeks with some new interesting updates :)

Just for update, i think i found a solution for my problem, i am updating this thread so that it might be helpful for some guys.

In socket.js file add this code  under ```function socketConnection(socket){ ... }```
```javascript
	function LeaveBoard(name) {
		socket.leave(name);
	}
```
and on same page add this under ```socket.on('broadcast', noFail(function onBroadcast(message) { ... });```
```javascript
if(message.data.auth=="expired"){ 
			LeaveBoard(boardName);
			log("Leaving board...");
		}else{
			//Send data to all other users connected on the same board
			socket.broadcast.to(boardName).emit('broadcast', data);
			// Save the message in the board
			saveHistory(boardName, data);
}
```
Here in above code, we'll be sending "auth" value in every socket request body.

Thanks,
Rohit
