### ISSUE TITLE
Date format modification for tmp file

### ISSUE THREAD

**Issue by keropan** [lovasoa/whitebophir#28]
hi,

thanks for this tool. It is helpful.

Just a little thing, currently i need to run it under windows (no other choice at now) and i see an error.
when node tries to save the tmp file of board an error is occured.

the reason is due to date format used in backupFileName function.
This one is not comptatible  on Windows (error in fs.writeFile)
[](https://stackoverflow.com/questions/36696605/nodejs-in-windows-file-system-path-error-4058-enoent)

before

`function backupFileName(baseName) {
	return baseName + '.' + new Date().toISOString() + '.bak';
}`

after

```
function backupFileName(baseName) {
	//date format modifcation for Windows
	var mydate =  new Date().toISOString().replace(new RegExp(':','g'),'.');
	return baseName + '.' + mydate + '.bak';
}
```

it's work without any problem on Windows and Debian (under WSL)

hope this can be useful

Regards

K.

**Comment by lovasoa** [comment]
Thank you for the bug report. I am going to fix this.
