### ISSUE TITLE
Note: There is now a Sandstorm package for this app!

### ISSUE THREAD

**Issue by ocdtrekkie** [lovasoa/whitebophir#284]
Hello, I thought you might like to know I recently packaged WBO for Sandstorm. I need to finish filling out some of the metadata, but the experimental release is here: https://apps.sandstorm.io/app/rhtntjye2n7p71vrcq0ae4f6n9nr139fdk4n884tw55k40vy4uph?experimental=true (and the final one will be without the ?experimental=true once published).

Currently it is a very simple fork: As on Sandstorm, apps should preferably be single-document, the index.html has been replaced with a meta-refresh to a board named "board", and I had to clear out a call for os.userInfo() which fails in the Sandstorm environment.

**Comment by lovasoa** [comment]
Hello and thank you for making the package. Would you be interested to upstream your changes ?

 - the userInfo call could be wrapped in a try/catch
 - there could be a [configuration parameter](https://github.com/lovasoa/whitebophir/blob/master/server/configuration.js) to set a default board name.

This way, you could use the main branch of wbo in your sandstorm package.

**Comment by ocdtrekkie** [comment]
I would indeed, though I am not super confident I could quickly figure out how to implement the configuration parameter myself. (Someday I should learn to hack on JS codebases more...) With those changes the only thing the Sandstorm package would need to carry upstream would be the .sandstorm folder with packaging metadata.

**Comment by lovasoa** [comment]
For the configuration, it should not be more complicated than added an entry in the configuration file and than changing this:

https://github.com/lovasoa/whitebophir/blob/180c6d7e832c3f0ae32615e977a35630351cdeba/server/server.js#L224-L227

to make a redirection (a simple `response.writeHead(302, { location: '/boards/myboard' })` )

Don't hesitate to ask here if you need more guidance

**Comment by ocdtrekkie** [comment]
Okay, so subject to testing before I open the PR, but new edit for whitebophir should be:
https://github.com/ocdtrekkie/whitebophir/commit/12f4ea0b040f5cebb39c1f9a50d7895cff068989

And the following repo should clone whitebophir into a subdirectory (which it gitignores) and builds the Sandstorm package, so I can recklessly pile metadata the rest of the metadata I need in here.
https://github.com/ocdtrekkie/whitebophir-sandstorm
