### ISSUE TITLE
Linting and Formatting

### ISSUE THREAD

**Issue by atomdmac** [lovasoa/whitebophir#289]
@lovasoa How do you feel about adding linting and auto-formatting to the tooling for this project?  I'm happy to open a PR but I'm curious if there are any reservations about adding such a thing and if not, which settings would be preferred.  (ex. tab width, tabs vs. spaces, single vs. double quotes, etc.)

**Comment by lovasoa** [comment]
Hi ! Yes, I'm open to it, and don't have strong preferences for the style. Pick whatever is the closest to what is already there and leads to the smallest diff.

**Comment by bhavik001** [comment]
Hello @lovasoa and @atomdmac !
Can I work on this issue and can someone assign me this issue?

**Comment by lovasoa** [comment]
Sure ! Feel free to make a proposition and we'll iterate on it.

**Comment by bhavik001** [comment]
Hello @lovasoa !
I am added the pull request for the feature given above please review the pull request and let me know if I have to make any changes.

**Comment by bhavik001** [comment]
Hey @lovasoa 
Are you ok with the pull request I have created! Please let me know if I have to make any change then.
