### ISSUE TITLE
Formatting and Add formatting to CI workflow

### ISSUE THREAD

**Issue by bhavik001** [lovasoa/whitebophir#291]
Hey @lovasoa !
I want to add Formatting to the project and in the CI workflow can you assign me this issue? I am interested in working on it.

**Comment by bhavik001** [comment]
Hey @lovasoa !
I have added new pull request as you mention earlier. Can you please review and merge the pull request. Also can you assign me to this issue as I have to show it to my professor for my college work. Let me know if I have to make any changes.

**Comment by lovasoa** [comment]
Hello! You don't need to mention`@lovasoa` in every message, I get the notifications anyway :) I'll look at your new PR when I can, but keep in mind that everyone here is a volunteer. A reminder after some time of inactivity is fine, but you cannot expect volunteers to always answer answer your questions immediately. 

Also, if your goal is to get something merged quickly, you should probably try something with a smaller diff, and that more clearly benefits the project.

**Comment by bhavik001** [comment]
Okay
