### ISSUE TITLE
Docker WBO KO sur Synology

### ISSUE THREAD

**Issue by KaaR0l** [lovasoa/whitebophir#294]
Hello Lovasoa,
J'ai vu que tu es de Paris, je tente ma chance en Français :)

J'essaye d'installer WBO en mode Docker sur un NAS Synology DSM 7 mais l'image ne se lance pas.

Voici les logs d'exécution : 
```
Tâche : Install WBO
Heure de début : Tue, 28 Nov 2023 16:51:01 +0100
Heure d'arrêt : Tue, 28 Nov 2023 16:51:46 +0100
État actuel : 0 (Normal)
Sortie/erreur standard :
Unable to find image 'lovasoa/wbo:latest' locally
latest: Pulling from lovasoa/wbo
f56be85fc22e: Already exists
8f665685b215: Pulling fs layer
e5fca6c395a6: Pulling fs layer
561cb69653d5: Pulling fs layer
89026c4d9299: Pulling fs layer
8d5e737447dc: Pulling fs layer
6573b6755fc1: Pulling fs layer
89026c4d9299: Waiting
8d5e737447dc: Waiting
4ab63c794859: Pulling fs layer
2b80c351ccf2: Pulling fs layer
6573b6755fc1: Waiting
4ab63c794859: Waiting
2b80c351ccf2: Waiting
561cb69653d5: Verifying Checksum
561cb69653d5: Download complete
e5fca6c395a6: Verifying Checksum
e5fca6c395a6: Download complete
89026c4d9299: Verifying Checksum
89026c4d9299: Download complete
8f665685b215: Verifying Checksum
8f665685b215: Download complete
8d5e737447dc: Verifying Checksum
8d5e737447dc: Download complete
6573b6755fc1: Verifying Checksum
6573b6755fc1: Download complete
2b80c351ccf2: Verifying Checksum
2b80c351ccf2: Download complete
4ab63c794859: Verifying Checksum
4ab63c794859: Download complete
8f665685b215: Pull complete
e5fca6c395a6: Pull complete
561cb69653d5: Pull complete
89026c4d9299: Pull complete
8d5e737447dc: Pull complete
6573b6755fc1: Pull complete
4ab63c794859: Pull complete
2b80c351ccf2: Pull complete
Digest: sha256:303c57e69d1039a9ab290b4ee8f29e615b59be1f27a7fbb10aa394608d4d51b3
Status: Downloaded newer image for lovasoa/wbo:latest
b8f228f37350706a2eab7337ad568b210cf0b2b00315e718becd336968582392

```
Je suis désolée, mais je n'y comprends rien ! :D
Pourrais-tu m'aider stp ?
Qu'est-ce que je fais mal ?

Voici les commandes que j'utilise pour l'installation sur Docker :  

```
docker run -d --name=wbo \
-p 5479:80 \
-v /volume1/docker/wbo:/opt/app/server-data \
--restart always \
lovasoa/wbo
chown -R 1000:1000 /volume1/docker/wbo
```
Je les ai trouvées ici : https://mariushosting.com/how-to-install-wbo-on-your-synology-nas/
(je serais bien incapable de les écrire moi-même !!)

Merci beaucoup pour ton aide ! :)
Carole.

PS : j'ai déjà installé pas mal d'autres conteneur grâce au site mariushosting.com et je n'avais jamais eu de problème

**Comment by lovasoa** [comment]
Bonjour,
  Il n'y a pas d'erreur dans les logs que vous mentionnez :) Je ne connais pas synology, mais peut-être devriez-vous demander de l'aide à la personne qui a écrit ce tutoriel ?

**Comment by lovasoa** [comment]
Vous pouvez toujours commenter ci-dessous, mais je préfère fermer l'issue si ce n'est pas un problème avec wbo.

**Comment by KaaR0l** [comment]
Bonjour,
Et merci pour votre réponse.
Je vais chercher de l'autre côté.
Bonne journée,
Carole.

**Comment by lovasoa** [comment]
Bonne journée à vous ! N'hésitez pas à poster ici si vous trouvez une solution, ou si vous trouvez des logs d'erreurs de wbo.

**Comment by lovasoa** [comment]
@mariushosting : thanks ! this is a useful report. I'll look into it.

**Comment by lovasoa** [comment]
Looks like our arm image builds don't work anymore, which prevents anything from being pushed to docker.

I manually updated images for intel and arm64: https://hub.docker.com/repository/docker/lovasoa/wbo/general

As for the port binding error, I'm not sure it's related, but you can always specify the port on which you want to have wbo listen. Your launch command could look like this:

```sh
docker run -d --name=wbo -p 5479:5479 -e PORT=5479 -v /volume1/docker/wbo:/opt/app/server-data --restart always lovasoa/wbo:latest
```

**Comment by mariushosting** [comment]
> Looks like [our arm image builds don't work anymore](https://github.com/lovasoa/whitebophir/actions/runs/6657910862/job/18093660071), which prevents anything from being pushed to docker.
> 
> I manually updated images for intel and arm64: https://hub.docker.com/repository/docker/lovasoa/wbo/general
> 
> As for the port binding error, I'm not sure it's related, but you can always specify the port on which you want to have wbo listen. Your launch command could look like this:
> 
> ```shell
> docker run -d --name=wbo -p 5479:5479 -e PORT=5479 -v /volume1/docker/wbo:/opt/app/server-data --restart always lovasoa/wbo:latest
> ```

This completely solved the issue!

Thank you for the effort @lovasoa
