### ISSUE TITLE
Is there a way to disable the public board?

### ISSUE THREAD

**Issue by losdelfuego** [lovasoa/whitebophir#303]
I'd love to run this without a publicly available board, ideally only named private boards. Is there a way to do that?

**Comment by lovasoa** [comment]
Hello ! 
  The public board is nothing but a normal board named "anonymous". The only thing that makes it special is the prominent link to it from the home page. You can write a different home page for your installation if you want, either by overwriting [`client-data/index.html`](https://github.com/lovasoa/whitebophir/blob/master/client-data/index.html) or by putting a reverse proxy in front of SQLPage. For instance

```nginx
server {
    listen 80;
    server_name yourdomain.com;  # Replace with your actual domain

    location = / {
        # Replace 'custom_home.html' with the actual filename of your custom HTML file
        alias /path/to/custom_home.html;
        try_files $uri =404;
    }

    location / {
        # Proxy requests to the service running on port 3001
        proxy_pass http://127.0.0.1:5001;  # Change the port if needed
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Additional server configuration goes here if necessary
}
```

**Comment by losdelfuego** [comment]
Thanks! I'm already using a reverse proxy on my build, and since I'm running in a docker container, the custom home route might be the way to go. Pointing to the correct links will be tricky regardless with a Docker installation, so a customizable home page could be useful.
