### ISSUE TITLE
Board "pages"

### ISSUE THREAD

**Issue by losdelfuego** [lovasoa/whitebophir#304]
Enhancement request:
It would be useful to have "pages", like Google's Jamboard has, per board. Use cases:
- you could have one board for an educational course, with different pages for different lessons
- you could have a single whiteboard for brainstorming with a team, with pages aligning to individual brainstorming sessions

**Comment by lovasoa** [comment]
WBO whiteboards are already infinite, nothing prevents you to draw rectangles on them and can them pages, to give structure to your boards
