### ISSUE TITLE
Download SVG without Browser

### ISSUE THREAD

**Issue by nesges** [lovasoa/whitebophir#315]
Is there any way to download a rendering of a board without the use of a browser?

We're running an anonymous board which is used quite a lot, but on occasion draws attention from people that think swastikas and racist bs are fun. To monitor the board I've setup a puppeteer script to take a daily screenshot and send it to our discord. Problem is, the board has grown to about 34MB of JSON-Data and puppeteer consumes to much memory from our small machine to render the image reliably. Now I'm seeking to avoid swiping the anonymous board

**Comment by lovasoa** [comment]
Hi !
  You can download the board as SVG at `/preview/{boardName}`. The renderer is not 100% faithful, but it's often good enough to get a preview. For instance, you can see the official anonymous whiteboard in SVG at https://wbo.ophir.dev/preview/anonymous

  We should also document that. Can you make a small PR to the README ?

**Comment by nesges** [comment]
That's perfect! Thank you! I'll make the PR
