### ISSUE TITLE
links with relative path

### ISSUE THREAD

**Issue by AnCaRioN** [lovasoa/whitebophir#32]
Hi,

I try to deploy wbo with docker, behind an apache webserver with proxypass because I want to use it as a subsection of a website : https://www.toto.fr/wbo

But some resources are in absolute path, when I try to access https://www.toto.fr/wbo/boards/test, /background.png, /socket.io/socket.io.js, /js/canvascolor/canvascolor.min.js gets 404 or 500 error code.

Or maybe I made a mistake in my apache conf ?

```
<Location /wbo>
        ProxyPass "http://wbo.host.fr:5001/"
        ProxyPassReverse "http://wbo.host.fr:5001/"
</Location>
```

**Comment by lovasoa** [comment]
Hello !
  Currently, wbo needs to be run at the root of a domain. That means you can run it at `https://wbo.toto.fr` or `https://toto.fr:8080`. 
  This limitation simply comes from the fact that I've never needed to run WBO on another path. Adding this capability shouldn't be hard, and a PR for this would be welcome :)

**Comment by lovasoa** [comment]
Looking at your apache config: couldn't you run wbo on port 80 instead of 5001 on `wbo.host.fr` ?

**Comment by AnCaRioN** [comment]
> Looking at your apache config: couldn't you run wbo on port 80 instead of 5001 on `wbo.host.fr` ?

I can, but it will change nothing, I can't expose wbo.host.fr to the internet, I want to proxyfy it to https://toto.fr/wbo.
And I can run wbo on port 5001 with a dedicated user, to run it on port 80 I need the root account.

**Comment by AnCaRioN** [comment]
> Hello !
> 
> Currently, wbo needs to be run at the root of a domain. That means you can run it at `https://wbo.toto.fr` or `https://toto.fr:8080`, but not `https://toto.fr/wbo`.
> 
> This limitation simply comes from the fact that I've never needed to run WBO on another path. Adding this capability shouldn't be hard, and a PR for this would be welcome :) It should just be a matter of adding an environment variable `WEB_ROOT`, and passing its value to html templates in `client-data`

I can take a look, but I'm not a developper, I just need time to look at the code and tune it.
