### ISSUE TITLE
Remove wbo-backup.zip

### ISSUE THREAD

**Issue by iblech** [lovasoa/whitebophir#33]
I believe the addition of `wbo-backup.zip` was in error. Maybe one of the rare cases where a force push might be in order? (Feel free to also delete this issue if you see fit.)

Thank you very much for WBO. Having compared many online collaborative whiteboard solutions, this is by far my favourite and a key ingredient to how I will conduct my university teaching this term. I'm currently packaging it for NixOS.

**Comment by lovasoa** [comment]
Hello, 
  I am really sorry for this leak. This backup was indeed pushed to github accidentally. I took the necessary steps, and removed it from git history.

Again, sorry for my mistake,
Ophir
