### ISSUE TITLE
On mobile, the size selector does not close when it is blurred

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/whitebophir#51]
The size selector stays open when the user starts drawing on mobile browsers (tested in chrome and firefox mobile).

See #49

**Comment by finnboeger** [comment]
Interesting, on which OS did you test? I tested it in Chrome and Firefox on Android on a tablet as well as a smartphone and had no issues.

**Comment by lovasoa** [comment]
I tested on mozilla firefox nightly 200427 and Google Chrome 81 on a OnePlus 5T. Both honored `hover: hover` media queries.

**Comment by finnboeger** [comment]
This seeems to be a bug with your phone, it seems like a few devices misreport their hover ability.
I added another check via `@media (pointer: coarse)` to catch those devices as well.

You can check what your device claims here:
https://googlechrome.github.io/samples/media-hover-pointer/
