### ISSUE TITLE
Bug: Can't preview or download boards with spaces

### ISSUE THREAD

**Issue by finnboeger** [lovasoa/whitebophir#69]
When running the latest master or prod branch and creating a board with a space in its name it is possible to draw on it just fine, however if one wants to download the board or render a preview the url gets encoded twice (first by the browser changing the space to `%20`, then again by the server changing it to `%2520`). 
For some reason this does not present an issue on the wbo.ophir.dev server although the same double encoding behaviour can be observed there

**Comment by lovasoa** [comment]
Good catch ! Board filenames used to be double-urlencoded due to a bug, and fixing it caused this.

**Comment by finnboeger** [comment]
I added a PR to solve this but that would possibly break the current production site if it uses a workaround to be able to deliver those double encoded files for download/preview

**Comment by lovasoa** [comment]
No, I used a small script to rename the existing filenames when I fixed the issue. The site wasn't as popular then as it is now.
