### ISSUE TITLE
Installation instructions for Ubuntu 20.04

### ISSUE THREAD

**Issue by elearningdienst** [lovasoa/whitebophir#75]
Just an information for german users an maybe a thing for the Wiki: 

I wrote a howto on installing WBO: https://eldshort.de/2092sz. It should be a kind of open educational ressource that IT teacher or in-company instructor can use to show their trainees how to deploy a service in Ubuntu/ Debian.

As WBO ist small, functional and really useful for collaboration it is in my opinion a ideal tool for learning in both meanings: build up IT competencies as well as using it as tool.

**Comment by lovasoa** [comment]
Great, thank you for sharing the link ! The [wiki](https://github.com/lovasoa/whitebophir/wiki) is open to contributions.

**Comment by lovasoa** [comment]
Also, out of curiosity: I see that you are advising users to install WBO by installing directly node and npm. Why did you choose that over docker ? The docker version is easier to setup and update (no git clone, no npm install) and more secure (you are not giving the code access to your filesystem or to other network interfaces).

**Comment by elearningdienst** [comment]
In my setting the whiteboard works in a unprivileged lxc container (CT) within a Proxmox server. So I prefer an direct installation. It is very lightweight and worked out of the box. With balooning harddisk and memory. 

Due the handwork it is a litte more "complicated" than pulling an docker image. The youngsters should learn ;-) while installing.

BTW: I don't habe an idea how that worked with the wiki in guithub/gitlab.
