### ISSUE TITLE
Client's pencil tool discards strokes

### ISSUE THREAD

**Issue by cfeck** [lovasoa/whitebophir#81]
In the "move" listener of the "pencil" tool, there is a 70 ms check, probably to avoid sending data to the server too fast. I suggest to decouple drawing and sending.

Right now, it happens that it silently discards strokes (see steps to reproduce below).

Steps to reproduce:
* select the pencil tool
* draw a "V" letter with the stylus quickly

Actual result:
* either a single line is drawn, or an "U" shape

Expected result:
* V shape

Suggested fix:
* collect more data points for drawing and (ideally) draw on each listener event
* try to simplify the resulting path by discarding intermediate points that are close to the path to avoid sending too many data points
* update the server by sending differences of the resulting path e.g. every 100 ms

**Comment by lovasoa** [comment]
Hello,
  We could indeed improve how we handle path simplification. We currently indeed just sample the points every 70 ms. However, it doesn't prevent  users from quickly drawing a V shape...
![v_shape](https://user-images.githubusercontent.com/552629/82998788-6ef5b380-a008-11ea-8c65-0cbb95866c13.gif)

**Comment by cfeck** [comment]
Sorry, I wasn't clear, I was talking about "writing" instead of "drawing". So you have much smaller and much quicker strokes. You probably would need a stylus tablet to see the issue. Actually now that the test server works again, I see that writing on it is plainly unusable.

**Comment by ThreeCO** [comment]
> Sorry, I wasn't clear, I was talking about "writing" instead of "drawing". So you have much smaller and much quicker strokes. You probably would need a stylus tablet to see the issue. Actually now that the test server works again, I see that writing on it is plainly unusable.

I'll second that. It's quite difficult to write text with a digital pen (Apple Pencil).
As far as I have learned they are either discarded or massively rounded. In both ways it's difficult to read what is written.

**Comment by droundy** [comment]
I'll add that I see the same issue when writing with my Wacom One tablet.  I'd love to see this fixed ASAP and would be happy to contribute (with my rudimentary JavaScript skills and advanced programming skills), as I would like to use wbo whiteboards when teaching physics this fall, but that requires students to able to effectively write mathematical equations.  But I have know idea (of course) as to how one might go about fixing the issue.

**Comment by lovasoa** [comment]
Hello @droundy, and thank you for offering your help ! 
The first thing to do is to play with the two parameters I mentioned above: the [*angularity*](https://github.com/lovasoa/whitebophir/blob/master/client-data/tools/pencil/wbo_pencil_point.js#L57) and the [*sampling delay*](https://github.com/lovasoa/whitebophir/blob/master/client-data/tools/pencil/pencil.js#L63). If you want something that reproduces the input drawing more precisely (but is heavier to handle for the server, and less smooth), you should reduce the sampling delay and increase the angularity.

If you find no satisfying solution and want to go more in depth, a more long-term solution may be to change the algorithm in [`wbo_pencil_point.js`](https://github.com/lovasoa/whitebophir/blob/master/client-data/tools/pencil/wbo_pencil_point.js) and the way we send lines to the server. Ideally, I would like to take into account all the points we receive, then compute a bezier curve interpolation, then send only this interpolation to the server. This should leave us with something that is both closer to what the user has drawn and lighter to the server, while still being smooth enough.

**Comment by dazsmith** [comment]
This discussion was very helpful for me. Thanks! I found that decreasing the sampling delay to 20ms made it work quite well with my pen. When I tried increasing the angularity I found many vertices being dropped, so I left that setting alone.

**Comment by droundy** [comment]
Hi @dazsmith  I sort of get good results on my whiteboard as I write rapidly by simply decreasing the sampling delay.  At 20ms it seems to work roughly fine when run on my computer as localhost.

However, if I set the sampling delay shorter I'm also seeing that another client logged into the same whiteboard is missing many of the letters!  :(  I am surprised that there does not seem to be eventual consistency in the display of the whiteboards.  If the whiteboard I'm writing on (quickly) is refreshed, it gets to see the missing and malformed letters also.  Is this another bug that needs reporting separately? I worry that students with a poor internet connection and bandwidth that is being hogged by zoom might end up with something unusable.  And it's especially problematic if a student can't *see* that their writing is coming out mangled!

**Comment by lovasoa** [comment]
@droundy : The behavior you are describing looks like the server's max emit count was triggered. As a protection against Denial of Service attacks, the server limits the number of messages that a single user can send per unit of time. When you lowered the sampling delay, the client started to send more messages per second, and the server thought the client was trying to flood it. You can change the flooding detection limits with the following environment variables on the server : 
 - `WBO_MAX_EMIT_COUNT` 
 - `WBO_MAX_EMIT_COUNT_PERIOD`

If your server can handle it, you can set, for instance `WBO_MAX_EMIT_COUNT=10000 WBO_MAX_EMIT_COUNT_PERIOD=60000` to allow up to 10000 messages (strokes) per minute per client.

(See https://github.com/lovasoa/whitebophir/blob/master/server/configuration.js#L29-L33 )

**Comment by lovasoa** [comment]
@droundy updated the pencil tool, and I changed the default server limits to be 50% more generous in terms of number of updates per second. I deployed the changes to [wbo.ophir.dev](https://wbo.ophir.dev). Let me know if the situation improved.

**Comment by cfeck** [comment]
Sorry for the late feedback, but today I could test it, and it works perfectly. Thank you!
