### ISSUE TITLE
New listener for tools

### ISSUE THREAD

**Issue by Sharath-GitBan** [lovasoa/whitebophir#89]
Hi Team,

I was going through code for each tool in the app, right now the listeners available for each tool are press, move and release. Can I add new listeners like click or db click or hover etc to the existing code.
It'll be helpful if you can help me on this.

**Comment by lovasoa** [comment]
Hello,
  Yes, you can use any DOM event as a listener, just add it to the `compiledListeners` property of your tool. 

```js
	var myTool = {
		"name": "MyNewTool",
		"shortcut": "m",
		"listeners": {
			"press": startLine,
			"move": continueLine,
			"release": stopLineAt,
		},
               "computedListeners": {
                       "dblclick": myListener
               }, ...
```

For hover, I would use the existing move listener, though. See for instance the eraser.

The relevant part of the code you may want to read is here : https://github.com/lovasoa/whitebophir/blob/master/client-data/js/board.js#L497-L513

**Comment by Sharath-GitBan** [comment]
Hello, thank you for your response, I added 'click' listener to the tool, but when I click after selecting the tool, even listener is not triggered.

**Comment by lovasoa** [comment]
If you publish your fork, I'll have a look at it if you want.

**Comment by Sharath-GitBan** [comment]
It should be **compiledListeners** not computedListeners

**Comment by lovasoa** [comment]
Oh, I see. I wrote the right name in my message above, but made a mistake in the example.
