### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by TWINGSISTER** [lovasoa/whitebophir#91]
I discovered this wonderful work and searched issues and found nothing about this so I dare to ask.
It is difficult for me to find a free server to install Sandstorm. I would be glad to propose my colleagues this environment but I would like to bring them to  a computer lab and ask them to follow a procedure so that at the end they have their own copy running for free and possibly with no credit card. So things like AWS are out.
Probably you can do that for an unlimited time onto Heroku free tier and onto IBM  Cloud. One year free tier from Pivotal and two months from Red Hat Open Shift. I couldn't find any other option. 
I think that deployment on Heroku could be the right way to go since I succeeded installing Huginn without installing Docker just pressing a button
https://elements.heroku.com/buttons/huginn/huginn
as in 
https://elements.heroku.com/buttons/huginn/huginn 
Can you help me in this?

**Comment by lovasoa** [comment]
Hello,
  The deployment instructions are in the readme: https://github.com/lovasoa/whitebophir#running-your-own-instance-of-wbo . They apply to any hosting provider. As long as you have SSH access to a machine, you can use the commands stated in the readme. If you do not have SSH access, then you should follow your provider's instructions about how to deploy Node.js applications.
  Is there a part of our README instructions that is not clear, or would require more details ? If so, let me know, and we can work together on improving the README.
